module.exports = {
  LOGIN: 'Logowanie',
  REGISTER: 'Rejestracja',
  LOGOUT: 'Wyloguj się',
  ADD_RECIPE: 'Dodaj przepis',
  SAVE: 'Zapisz',
  REMOVE: 'Usuń',
  CONFIRM: 'Potwiedź',
  EDIT: 'Edytuj',
  SUBMIT_LOGIN: 'Zaloguj się',
  SUBMIT_REGISTER: 'Zarejestruj się',
  SEARCH_INPUT: 'Wyszukaj przepis',
  RETURN: 'Powrót',
  RETURN_MAIN_PAGE: 'Powrót na główną stronę',
  RETURN_PREV_PAGE: 'Powrót na poprzednią stronę',
  LOGO: 'Logo',
};
